# Site settings
baseurl = "http://may1705.sd.ece.iastate.edu/"
languageCode = "en-us"
title = "Team 05 Portfolio"
theme = "hugo-agency-theme"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Team May1705 - Cattle Krush"
  description = "Helping ranchers stay one step ahead of the market"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Team 5"
    summary = "Summary"
    portfolio = "Mockups"
    weekly_reports = "Weekly Reports"
    presentations = "Presentations"
    team = "About Us"
    contact = "Contact Info"

    [[menu.postpend]]
     url = "https://docs.google.com/document/d/1r2jGtpfzgsy1-tWQ9DnQHK4rI6s-jWnPEPl70FV_JIw/edit?usp=sharing"
     name = "Design Document"
     weight = 10
    [[menu.postpend]]
     url = "https://docs.google.com/document/d/1FFCXcG5K97WREelkpD-ol_I10lQjhgHioQcs_KUAT5U/edit?usp=sharing"
     name = "Project Plan"
     weight = 10

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the valarc="https://docs.google.com/presentation/d/1SGkPyWYjqUohAEAfU2JleJZwLIB5I1XuAyGkUs7nBRI/embed?start=false&loop=false&delayms=3000" frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>s with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Welcome To Our Project Website!"
    subtitle = "Want to know more about Cattle Krush?"
    buttonText = "Check it out!"



  # Summary section
  # We should include what the project is, why it matters, and a blurb about performance livestock analytics
  [params.summary]
    enable = true
    title = "The Project: Cattle Krush"
    subtitle = "A multi-platform tool for navigating the cattle futures market."

    [[params.summary.row]]

# See a cheatsheet of font-awesome icons here http://fontawesome.io/cheatsheet/

    [[params.summary.row.list]]
      icon = " fa-exclamation"
      title = "The Problem"
      description = "Every year farmers across America lose hundreds of thousands of dollars selling their head. Keeping track of each individual head's feed, weight, age, and health is an overwhelming task to do be hand. On top of this, the Chicago Stock Exchange only provides room for profit a few hours each week."

    [[params.summary.row.list]]
      icon = " fa-lightbulb-o"
      title = "The Solution"
      description = "Cattle Krush allows farmers to track every aspect of each individual head's health. It automatically calculates useful figures such as the cost of feeding head to a certain weight, or how long it will take for a head to reach its target weight. It also offers live notifications to the farmer when their head can be sold for a profit on the Chicago Stock Exchange."

    [[params.summary.row.list]]
      icon = "fa-plus"
      title = "Implications"
      description = "With Cattle Krush, farmers are finally able to effectively track their cattle's growth, and consistantly sell them for a profit on the open market. Cattle Krush is the future of livestock management."

  # Mockups section
  #
  # We should include each of the Cattle Krush screen
  # mockups and an explanation of how they work
  [params.portfolio]
    enable = true
    # All mockups defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Screen Mockups"
    subtitle = "Click on the mockups to see each screen the Cattle Krush has to offer."

    [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close project"


  # Weekly Reports Section
  [params.weekly_reports]
    enable = true
    title = "Weekly Reports"
    subtitle = "The steady march of progress"
    drive_folder_id = "0B6EBAgXsSbcSS25UM2FCZkhzTUk"

  [params.presentations]
    enable = true
    title = "Presentations"
    subtitle = "Check out how well things have gone!"

    [[params.presentations.list]]
      name = "Semester 1 Pesentation - 12/07/2016"
      presentation_id = "1SGkPyWYjqUohAEAfU2JleJZwLIB5I1XuAyGkUs7nBRI"

  # Team section
  [params.team]
    enable = true
    title = "Meet the team"
    subtitle = "Learn more about each member by visiting their profiles."
    description = "Our team consists of six Iowa State University students. We are all enrolled in our final year at ISU, and are working together over the next couple months to complete our senior project in tandem with the wonderful startup Performance Livestock Analytics"

    # All team member's pictures are stored under 'themes/hugo-agency-theme/static/img/team'.
    # Replace them with your own too.
    [[params.team.members]]
      img = "mitch.jpg"
      name = "Mitchell Borman"
      social = [
	["fa-github", "https://github.com/mfborman"],
        ["fa-linkedin", "https://www.linkedin.com/in/mitchell-borman-587987105"]
      ]

    [[params.team.members]]
      img = "taylor.jpg"
      name = "Taylor Dugger"
      social = [
	["fa-github", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.team.members]]
      img = "ray.jpg"
      name = "Raymond Kinsella"
      social = [
	["fa-github", "https://github.com/kinsella333"],
        ["fa-linkedin", "https://www.linkedin.com/in/ray-kinsella-692376b0"]
      ]

    [[params.team.members]]
      img = "joe.jpg"
      name = "Joseph McGovern"
      social = [
	["fa-github", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.team.members]]
      img = "tyler.jpg"
      name = "Tyler Stapler"
      social = [
	["fa-github", "https://github.com/tstapler"],
        ["fa-linkedin", "https://www.linkedin.com/in/tstapler"]
      ]

    [[params.team.members]]
      img = "austin.jpg"
      name = "Austin Yurchik"
      social = [
	["fa-github", "https://github.com/ayurchik"],
        ["fa-linkedin", "https://www.linkedin.com/in/austin-yurchik-034043122"]
      ]

  # Contact section
  [params.contact]
    enable = true
    title = "Contact Information"
    subtitle  = "Direct your comments here"
    buttonText = "Send message"

  [[params.contact.methods]]
    desc = "Email All Of Us On Our Iowa State Accounts"
    icon = "envelope"
    text = "may1705@iastate.edu"

  [[params.contact.methods]]
    desc = "Shared Group Email"
    icon = "envelope"
    text = "livestock.may1705@gmail.edu"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Published under the Apache License 2.0."
  [[params.footer.quicklinks]]
    text = "Get this bootstrap theme!"
    link = "https://startbootstrap.com/template-overviews/agency/"
  [[params.footer.quicklinks]]
    text = "Check out this site's soucecode"
    link = "https://github.com/tstapler/senior-design-website"
